import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localfont from "next/font/local"
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const helavita = localfont({
//   src: [{
//     path: '../public/fonts/helavita-compressed.otf',
//     weight: "600"
//   }],
//   variable: "--font-helavita"
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className + `${inter.className}  dark`}>{children}</body>
    </html>
  );
}
